#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VolleyballApp.Resource", IsApplication=true)]

namespace VolleyballApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Date = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TitleText1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int TitleText2 = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int btnLogin = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int listEvents = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int passwordText = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int registrierenText = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int usernameText = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListEvents = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LogIn = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
