#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VolleyballApp.Resource", IsApplication=true)]

namespace VolleyballApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int positions = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int common_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_signin_btn_text_light = 2131099659;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_btn_check_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_btn_check_off_disabled_focused_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_btn_check_off_disabled_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_btn_check_off_focused_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptheme_btn_check_off_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int apptheme_btn_check_off_pressed_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int apptheme_btn_check_on_disabled_focused_holo_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int apptheme_btn_check_on_disabled_holo_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int apptheme_btn_check_on_focused_holo_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int apptheme_btn_check_on_holo_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int apptheme_btn_check_on_pressed_holo_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int apptheme_textfield_activated_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int apptheme_textfield_default_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int apptheme_textfield_disabled_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int apptheme_textfield_focused_holo_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int check = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_full_open_on_phone = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_ic_googleplayservices = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_disabled_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_disabled_focus_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_disabled_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_focus_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_focus_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_icon_normal_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_icon_normal_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_icon_pressed_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_icon_pressed_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_disabled_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_disabled_focus_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_disabled_focus_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_disabled_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_focus_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_focus_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_text_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_signin_btn_text_normal_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_signin_btn_text_normal_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_signin_btn_text_pressed_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_signin_btn_text_pressed_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int delete = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int divider = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int edit_text = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Icon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int list_selector = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int list_selector_bg = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int menu_invite = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int NormalButton = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int pushnotification_icon = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int responsive_text = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int RoundButton = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int volleyballapp_logo = 2130837559;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0030
			public const int Date = 2131361840;
			
			// aapt resource value: 0x7f0a0025
			public const int EventDetails_Count_Abgesagt = 2131361829;
			
			// aapt resource value: 0x7f0a0028
			public const int EventDetails_Count_Eingeladen = 2131361832;
			
			// aapt resource value: 0x7f0a0022
			public const int EventDetails_Count_Zugesagt = 2131361826;
			
			// aapt resource value: 0x7f0a0024
			public const int EventDetails_LinearLayout_Abgesagt = 2131361828;
			
			// aapt resource value: 0x7f0a0027
			public const int EventDetails_LinearLayout_Eingeladen = 2131361831;
			
			// aapt resource value: 0x7f0a0021
			public const int EventDetails_LinearLayout_Zugesagt = 2131361825;
			
			// aapt resource value: 0x7f0a0026
			public const int EventDetails_ListUser_Abgesagt = 2131361830;
			
			// aapt resource value: 0x7f0a0029
			public const int EventDetails_ListUser_Eingeladen = 2131361833;
			
			// aapt resource value: 0x7f0a0023
			public const int EventDetails_ListUser_Zugesagt = 2131361827;
			
			// aapt resource value: 0x7f0a003b
			public const int FlyOutContainer = 2131361851;
			
			// aapt resource value: 0x7f0a0046
			public const int FlyOutContent = 2131361862;
			
			// aapt resource value: 0x7f0a004f
			public const int FlyOutMenu = 2131361871;
			
			// aapt resource value: 0x7f0a0041
			public const int InviteUserDialogCheckbox = 2131361857;
			
			// aapt resource value: 0x7f0a0040
			public const int InviteUserDialogUserName = 2131361856;
			
			// aapt resource value: 0x7f0a003d
			public const int InviteUserDialog_ListUser = 2131361853;
			
			// aapt resource value: 0x7f0a003c
			public const int InviteUserDialog_NoUser = 2131361852;
			
			// aapt resource value: 0x7f0a003f
			public const int InviteUserDialog_btnAbbrechen = 2131361855;
			
			// aapt resource value: 0x7f0a003e
			public const int InviteUserDialog_btnEinladen = 2131361854;
			
			// aapt resource value: 0x7f0a0049
			public const int MenuButton = 2131361865;
			
			// aapt resource value: 0x7f0a002c
			public const int Text = 2131361836;
			
			// aapt resource value: 0x7f0a002e
			public const int TitleText1 = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int TitleText2 = 2131361839;
			
			// aapt resource value: 0x7f0a00cb
			public const int UserDetailsDialog_BtnRemove = 2131361995;
			
			// aapt resource value: 0x7f0a00ca
			public const int UserDetailsDialog_BtnRemoveLine = 2131361994;
			
			// aapt resource value: 0x7f0a00bf
			public const int UserDetailsDialog_Name = 2131361983;
			
			// aapt resource value: 0x7f0a00c5
			public const int UserDetailsDialog_NumberLable = 2131361989;
			
			// aapt resource value: 0x7f0a00c4
			public const int UserDetailsDialog_NumberLine = 2131361988;
			
			// aapt resource value: 0x7f0a00c6
			public const int UserDetailsDialog_NumberValue = 2131361990;
			
			// aapt resource value: 0x7f0a00c8
			public const int UserDetailsDialog_PositionLable = 2131361992;
			
			// aapt resource value: 0x7f0a00c7
			public const int UserDetailsDialog_PositionLine = 2131361991;
			
			// aapt resource value: 0x7f0a00c9
			public const int UserDetailsDialog_PositionValue = 2131361993;
			
			// aapt resource value: 0x7f0a00c0
			public const int UserDetailsDialog_Role = 2131361984;
			
			// aapt resource value: 0x7f0a00c2
			public const int UserDetailsDialog_UserTypeLable = 2131361986;
			
			// aapt resource value: 0x7f0a00c1
			public const int UserDetailsDialog_UserTypeLine = 2131361985;
			
			// aapt resource value: 0x7f0a00c3
			public const int UserDetailsDialog_UserTypeValue = 2131361987;
			
			// aapt resource value: 0x7f0a00cc
			public const int UserListViewName = 2131361996;
			
			// aapt resource value: 0x7f0a00cd
			public const int UserListViewPosition = 2131361997;
			
			// aapt resource value: 0x7f0a0008
			public const int addEventBeginText = 2131361800;
			
			// aapt resource value: 0x7f0a000e
			public const int addEventEndDate = 2131361806;
			
			// aapt resource value: 0x7f0a000c
			public const int addEventEndDateLine = 2131361804;
			
			// aapt resource value: 0x7f0a0010
			public const int addEventEndDateTimeValue = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int addEventEndDateValue = 2131361807;
			
			// aapt resource value: 0x7f0a000d
			public const int addEventEndText = 2131361805;
			
			// aapt resource value: 0x7f0a0006
			public const int addEventEventDescriptionValue = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int addEventLocation = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int addEventName = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int addEventScrollView = 2131361795;
			
			// aapt resource value: 0x7f0a0009
			public const int addEventStartDate = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int addEventStartDateLine = 2131361799;
			
			// aapt resource value: 0x7f0a000b
			public const int addEventStartDateTimeValue = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int addEventStartDateValue = 2131361802;
			
			// aapt resource value: 0x7f0a0011
			public const int addEventTeamIdLabel = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int addEventTeamIdValue = 2131361810;
			
			// aapt resource value: 0x7f0a0019
			public const int addTeamBtnCreate = 2131361817;
			
			// aapt resource value: 0x7f0a0018
			public const int addTeamDescription = 2131361816;
			
			// aapt resource value: 0x7f0a0017
			public const int addTeamLocation = 2131361815;
			
			// aapt resource value: 0x7f0a0015
			public const int addTeamName = 2131361813;
			
			// aapt resource value: 0x7f0a0014
			public const int addTeamScrollView = 2131361812;
			
			// aapt resource value: 0x7f0a0016
			public const int addTeamSport = 2131361814;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a0035
			public const int btnAddEvent = 2131361845;
			
			// aapt resource value: 0x7f0a004b
			public const int btnAddInToolbar = 2131361867;
			
			// aapt resource value: 0x7f0a0013
			public const int btnCreateEvent = 2131361811;
			
			// aapt resource value: 0x7f0a004d
			public const int btnDeleteInToolbar = 2131361869;
			
			// aapt resource value: 0x7f0a004c
			public const int btnEditInToolbar = 2131361868;
			
			// aapt resource value: 0x7f0a002b
			public const int btnEventAbsagen = 2131361835;
			
			// aapt resource value: 0x7f0a002a
			public const int btnEventZusagen = 2131361834;
			
			// aapt resource value: 0x7f0a003a
			public const int btnFillDataOk = 2131361850;
			
			// aapt resource value: 0x7f0a0044
			public const int btnLogin = 2131361860;
			
			// aapt resource value: 0x7f0a0078
			public const int btnRegistration = 2131361912;
			
			// aapt resource value: 0x7f0a001f
			public const int eventDetailsEventDescriptionLine = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int eventDetailsEventDescriptionValue = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int eventDetailsScrollView = 2131361822;
			
			// aapt resource value: 0x7f0a002d
			public const int eventListHeader = 2131361837;
			
			// aapt resource value: 0x7f0a001c
			public const int eventLocation = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int eventState = 2131361819;
			
			// aapt resource value: 0x7f0a001d
			public const int eventTime = 2131361821;
			
			// aapt resource value: 0x7f0a001a
			public const int eventTitle = 2131361818;
			
			// aapt resource value: 0x7f0a0033
			public const int eventsFragmentBtnAddLine = 2131361843;
			
			// aapt resource value: 0x7f0a0039
			public const int fillDataFirstnameData = 2131361849;
			
			// aapt resource value: 0x7f0a0038
			public const int fillDataFirstnameLabel = 2131361848;
			
			// aapt resource value: 0x7f0a0037
			public const int fillDataNameData = 2131361847;
			
			// aapt resource value: 0x7f0a0036
			public const int fillDataNameLabel = 2131361846;
			
			// aapt resource value: 0x7f0a004e
			public const int fragmentContainer = 2131361870;
			
			// aapt resource value: 0x7f0a0047
			public const int frameLayout1 = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int linearLayout1 = 2131361864;
			
			// aapt resource value: 0x7f0a0031
			public const int listEvents = 2131361841;
			
			// aapt resource value: 0x7f0a0097
			public const int listStatistics = 2131361943;
			
			// aapt resource value: 0x7f0a0058
			public const int menuEventsPast = 2131361880;
			
			// aapt resource value: 0x7f0a0059
			public const int menuEventsTextPast = 2131361881;
			
			// aapt resource value: 0x7f0a0057
			public const int menuEventsTextUpcoming = 2131361879;
			
			// aapt resource value: 0x7f0a0056
			public const int menuEventsUpcoming = 2131361878;
			
			// aapt resource value: 0x7f0a005c
			public const int menuLogout = 2131361884;
			
			// aapt resource value: 0x7f0a005d
			public const int menuLogoutText = 2131361885;
			
			// aapt resource value: 0x7f0a0052
			public const int menuProfile = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int menuProfileText = 2131361875;
			
			// aapt resource value: 0x7f0a005a
			public const int menuStats = 2131361882;
			
			// aapt resource value: 0x7f0a005b
			public const int menuStatsText = 2131361883;
			
			// aapt resource value: 0x7f0a0055
			public const int menuTeam = 2131361877;
			
			// aapt resource value: 0x7f0a0054
			public const int menuTeamComplete = 2131361876;
			
			// aapt resource value: 0x7f0a005e
			public const int menuVersionText = 2131361886;
			
			// aapt resource value: 0x7f0a0032
			public const int noEvents = 2131361842;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0043
			public const int passwordText = 2131361859;
			
			// aapt resource value: 0x7f0a0071
			public const int profileBtnSave = 2131361905;
			
			// aapt resource value: 0x7f0a0072
			public const int profileErrorLine = 2131361906;
			
			// aapt resource value: 0x7f0a0073
			public const int profileErrorValue = 2131361907;
			
			// aapt resource value: 0x7f0a0063
			public const int profileNameLabel = 2131361891;
			
			// aapt resource value: 0x7f0a0062
			public const int profileNameLine = 2131361890;
			
			// aapt resource value: 0x7f0a0064
			public const int profileNameValue = 2131361892;
			
			// aapt resource value: 0x7f0a0069
			public const int profileNumberLabel = 2131361897;
			
			// aapt resource value: 0x7f0a0068
			public const int profileNumberLine = 2131361896;
			
			// aapt resource value: 0x7f0a006a
			public const int profileNumberValue = 2131361898;
			
			// aapt resource value: 0x7f0a006f
			public const int profilePasswordLabel = 2131361903;
			
			// aapt resource value: 0x7f0a006e
			public const int profilePasswordLine = 2131361902;
			
			// aapt resource value: 0x7f0a0070
			public const int profilePasswordValue = 2131361904;
			
			// aapt resource value: 0x7f0a0066
			public const int profilePositionLabel = 2131361894;
			
			// aapt resource value: 0x7f0a0065
			public const int profilePositionLine = 2131361893;
			
			// aapt resource value: 0x7f0a0067
			public const int profilePositionValue = 2131361895;
			
			// aapt resource value: 0x7f0a006c
			public const int profileTeamLabel = 2131361900;
			
			// aapt resource value: 0x7f0a006b
			public const int profileTeamLine = 2131361899;
			
			// aapt resource value: 0x7f0a006d
			public const int profileTeamValue = 2131361901;
			
			// aapt resource value: 0x7f0a0060
			public const int profileUserTypeLabel = 2131361888;
			
			// aapt resource value: 0x7f0a005f
			public const int profileUserTypeLine = 2131361887;
			
			// aapt resource value: 0x7f0a0061
			public const int profileUserTypeValue = 2131361889;
			
			// aapt resource value: 0x7f0a0075
			public const int registrationEmailData = 2131361909;
			
			// aapt resource value: 0x7f0a0074
			public const int registrationEmailLabel = 2131361908;
			
			// aapt resource value: 0x7f0a0077
			public const int registrationPasswordData = 2131361911;
			
			// aapt resource value: 0x7f0a0076
			public const int registrationPasswordLabel = 2131361910;
			
			// aapt resource value: 0x7f0a0045
			public const int registrierenText = 2131361861;
			
			// aapt resource value: 0x7f0a007c
			public const int requestListViewBtnAccept = 2131361916;
			
			// aapt resource value: 0x7f0a007d
			public const int requestListViewBtnDenie = 2131361917;
			
			// aapt resource value: 0x7f0a0079
			public const int requestListViewName = 2131361913;
			
			// aapt resource value: 0x7f0a007a
			public const int requestListViewText = 2131361914;
			
			// aapt resource value: 0x7f0a007b
			public const int requestListViewUserType = 2131361915;
			
			// aapt resource value: 0x7f0a0085
			public const int requestUserTypeBtnSendRequest = 2131361925;
			
			// aapt resource value: 0x7f0a007e
			public const int requestUserTypeRadioGroup = 2131361918;
			
			// aapt resource value: 0x7f0a0080
			public const int requestUserTypeRdbAdmin = 2131361920;
			
			// aapt resource value: 0x7f0a0082
			public const int requestUserTypeRdbCoremember = 2131361922;
			
			// aapt resource value: 0x7f0a0084
			public const int requestUserTypeRdbFan = 2131361924;
			
			// aapt resource value: 0x7f0a0083
			public const int requestUserTypeRdbMember = 2131361923;
			
			// aapt resource value: 0x7f0a0081
			public const int requestUserTypeRdbOperator = 2131361921;
			
			// aapt resource value: 0x7f0a007f
			public const int sound = 2131361919;
			
			// aapt resource value: 0x7f0a0086
			public const int spinnerDropDownTextViewName = 2131361926;
			
			// aapt resource value: 0x7f0a0087
			public const int spinnerTextViewName = 2131361927;
			
			// aapt resource value: 0x7f0a0093
			public const int statisticDetailsCountMatchdaysLable = 2131361939;
			
			// aapt resource value: 0x7f0a0094
			public const int statisticDetailsCountMatchdaysValue = 2131361940;
			
			// aapt resource value: 0x7f0a0095
			public const int statisticDetailsCountParticipatedMatchdaysLable = 2131361941;
			
			// aapt resource value: 0x7f0a0096
			public const int statisticDetailsCountParticipatedMatchdaysValue = 2131361942;
			
			// aapt resource value: 0x7f0a008f
			public const int statisticDetailsCountParticipatedTrainingsLable = 2131361935;
			
			// aapt resource value: 0x7f0a0090
			public const int statisticDetailsCountParticipatedTrainingsValue = 2131361936;
			
			// aapt resource value: 0x7f0a008d
			public const int statisticDetailsCountTrainingsLable = 2131361933;
			
			// aapt resource value: 0x7f0a008e
			public const int statisticDetailsCountTrainingsValue = 2131361934;
			
			// aapt resource value: 0x7f0a0089
			public const int statisticDetailsFrom = 2131361929;
			
			// aapt resource value: 0x7f0a0091
			public const int statisticDetailsMatchdayTitle = 2131361937;
			
			// aapt resource value: 0x7f0a0092
			public const int statisticDetailsMatchdayTitleProzentualValue = 2131361938;
			
			// aapt resource value: 0x7f0a0098
			public const int statisticDetailsSaison = 2131361944;
			
			// aapt resource value: 0x7f0a0088
			public const int statisticDetailsSaisonValue = 2131361928;
			
			// aapt resource value: 0x7f0a008a
			public const int statisticDetailsTill = 2131361930;
			
			// aapt resource value: 0x7f0a008b
			public const int statisticDetailsTrainingTitle = 2131361931;
			
			// aapt resource value: 0x7f0a008c
			public const int statisticDetailsTrainingTitleProzentualValue = 2131361932;
			
			// aapt resource value: 0x7f0a00a4
			public const int teamDetailsBtnFollow = 2131361956;
			
			// aapt resource value: 0x7f0a00a3
			public const int teamDetailsBtnJoin = 2131361955;
			
			// aapt resource value: 0x7f0a00a5
			public const int teamDetailsBtnLeave = 2131361957;
			
			// aapt resource value: 0x7f0a00b0
			public const int teamDetailsBtnRequestRank = 2131361968;
			
			// aapt resource value: 0x7f0a00b7
			public const int teamDetailsBtnSave = 2131361975;
			
			// aapt resource value: 0x7f0a00a2
			public const int teamDetailsFragmentContainer = 2131361954;
			
			// aapt resource value: 0x7f0a0099
			public const int teamDetailsHeadline = 2131361945;
			
			// aapt resource value: 0x7f0a00ac
			public const int teamDetailsHeadlineProfile = 2131361964;
			
			// aapt resource value: 0x7f0a00a9
			public const int teamDetailsHeadlineRequests = 2131361961;
			
			// aapt resource value: 0x7f0a009a
			public const int teamDetailsLocation = 2131361946;
			
			// aapt resource value: 0x7f0a00a6
			public const int teamDetailsMemberListMember = 2131361958;
			
			// aapt resource value: 0x7f0a00a7
			public const int teamDetailsMemberNoMember = 2131361959;
			
			// aapt resource value: 0x7f0a009c
			public const int teamDetailsName = 2131361948;
			
			// aapt resource value: 0x7f0a00b5
			public const int teamDetailsNumberLabel = 2131361973;
			
			// aapt resource value: 0x7f0a00b4
			public const int teamDetailsNumberLine = 2131361972;
			
			// aapt resource value: 0x7f0a00b6
			public const int teamDetailsNumberValue = 2131361974;
			
			// aapt resource value: 0x7f0a00b2
			public const int teamDetailsPositionLabel = 2131361970;
			
			// aapt resource value: 0x7f0a00b1
			public const int teamDetailsPositionLine = 2131361969;
			
			// aapt resource value: 0x7f0a00b3
			public const int teamDetailsPositionValue = 2131361971;
			
			// aapt resource value: 0x7f0a00ab
			public const int teamDetailsProfileLayout = 2131361963;
			
			// aapt resource value: 0x7f0a00aa
			public const int teamDetailsRequestList = 2131361962;
			
			// aapt resource value: 0x7f0a00a8
			public const int teamDetailsRequestsLayout = 2131361960;
			
			// aapt resource value: 0x7f0a009b
			public const int teamDetailsSport = 2131361947;
			
			// aapt resource value: 0x7f0a009e
			public const int teamDetailsTabMember = 2131361950;
			
			// aapt resource value: 0x7f0a009f
			public const int teamDetailsTabMemberUnderline = 2131361951;
			
			// aapt resource value: 0x7f0a00a0
			public const int teamDetailsTabProfile = 2131361952;
			
			// aapt resource value: 0x7f0a00a1
			public const int teamDetailsTabProfileUnderline = 2131361953;
			
			// aapt resource value: 0x7f0a009d
			public const int teamDetailsTabs = 2131361949;
			
			// aapt resource value: 0x7f0a00ae
			public const int teamDetailsUserTypeLabel = 2131361966;
			
			// aapt resource value: 0x7f0a00ad
			public const int teamDetailsUserTypeLine = 2131361965;
			
			// aapt resource value: 0x7f0a00af
			public const int teamDetailsUserTypeValue = 2131361967;
			
			// aapt resource value: 0x7f0a00ba
			public const int teamListViewName = 2131361978;
			
			// aapt resource value: 0x7f0a00b8
			public const int teamListViewOrt = 2131361976;
			
			// aapt resource value: 0x7f0a00b9
			public const int teamListViewSport = 2131361977;
			
			// aapt resource value: 0x7f0a00be
			public const int teamsFragmentBtnAdd = 2131361982;
			
			// aapt resource value: 0x7f0a00bd
			public const int teamsFragmentBtnAddLine = 2131361981;
			
			// aapt resource value: 0x7f0a00bb
			public const int teamsFragmentListTeams = 2131361979;
			
			// aapt resource value: 0x7f0a00bc
			public const int teamsFragmentNoTeams = 2131361980;
			
			// aapt resource value: 0x7f0a0050
			public const int textView1 = 2131361872;
			
			// aapt resource value: 0x7f0a004a
			public const int textView2 = 2131361866;
			
			// aapt resource value: 0x7f0a0042
			public const int usernameText = 2131361858;
			
			// aapt resource value: 0x7f0a0034
			public const int verticalSeparator = 2131361844;
			
			// aapt resource value: 0x7f0a0051
			public const int view1 = 2131361873;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEvent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddTeamFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EventListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EventsFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FillData = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FlyOutContainer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int InviteUserDialog = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int InviteUserDialogListView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LogIn = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MenuLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ProfileFragment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Registration = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int RequestListView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int RequestUserType = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SpinnerCheckedLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SpinnerTextView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int StatisticDetails = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int StatisticFragment = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int StatisticListView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TeamDetailsFragment = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int TeamDetailsMemberFragment = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int TeamDetailsProfileFragment = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int TeamListView = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int TeamsFragment = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int UserDetailsDialog = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int UserListView = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int server = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050023
			public const int app_name = 2131034147;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int common_android_wear_notification_needs_update_text = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int common_android_wear_update_text = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int common_android_wear_update_title = 2131034127;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_api_unavailable_text = 2131034141;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_enable_button = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_enable_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_enable_title = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_install_button = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_install_text_phone = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_install_text_tablet = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_install_title = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_invalid_account_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_invalid_account_title = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_needs_enabling_title = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_network_error_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_network_error_title = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_notification_needs_update_title = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_notification_ticker = 2131034114;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_sign_in_failed_text = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_sign_in_failed_title = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_unknown_issue = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_unsupported_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_unsupported_title = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_update_button = 2131034139;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_text = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_update_title = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_updating_text = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_updating_title = 2131034130;
			
			// aapt resource value: 0x7f05001c
			public const int common_open_on_phone = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int common_signin_button_text = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int common_signin_button_text_long = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int hello = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int position_prompt = 2131034148;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int button = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int checkBox = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int editText = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int listView = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int responsiveText = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int spinnerDropDownItemStyle = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int spinnerItemStyle = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int text = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int toolbarIcon = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
