#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VolleyballApp.Resource", IsApplication=true)]

namespace VolleyballApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int Date = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int EventDetails_ListUser = 2131099664;
			
			// aapt resource value: 0x7f06001f
			public const int FlyOutContainer = 2131099679;
			
			// aapt resource value: 0x7f060024
			public const int FlyOutContent = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int FlyOutMenu = 2131099690;
			
			// aapt resource value: 0x7f060027
			public const int MenuButton = 2131099687;
			
			// aapt resource value: 0x7f060013
			public const int Text = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int TitleText1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int TitleText2 = 2131099669;
			
			// aapt resource value: 0x7f060034
			public const int UserListViewEventState = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int UserListViewName = 2131099699;
			
			// aapt resource value: 0x7f060003
			public const int addEventBeginText = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int addEventEndDate = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int addEventEndDateTimeValue = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int addEventEndDateValue = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int addEventEndText = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int addEventLocation = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int addEventName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int addEventScrollView = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int addEventStartDate = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int addEventStartDateTimeValue = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int addEventStartDateValue = 2131099653;
			
			// aapt resource value: 0x7f060019
			public const int btnAddEvent = 2131099673;
			
			// aapt resource value: 0x7f06000b
			public const int btnCreateEvent = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int btnEventAbsagen = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int btnEventZusagen = 2131099665;
			
			// aapt resource value: 0x7f06001e
			public const int btnFillDataOk = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int btnLogin = 2131099682;
			
			// aapt resource value: 0x7f060032
			public const int btnRegistration = 2131099698;
			
			// aapt resource value: 0x7f06000e
			public const int eventLocation = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int eventState = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int eventTime = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int eventTitle = 2131099660;
			
			// aapt resource value: 0x7f06001d
			public const int fillDataFirstnameData = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int fillDataFirstnameLabel = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int fillDataNameData = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int fillDataNameLabel = 2131099674;
			
			// aapt resource value: 0x7f060029
			public const int fragmentContainer = 2131099689;
			
			// aapt resource value: 0x7f060025
			public const int frameLayout1 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int linearLayout1 = 2131099686;
			
			// aapt resource value: 0x7f060017
			public const int listEvents = 2131099671;
			
			// aapt resource value: 0x7f06002d
			public const int menuLogout = 2131099693;
			
			// aapt resource value: 0x7f060021
			public const int passwordText = 2131099681;
			
			// aapt resource value: 0x7f06002f
			public const int registrationEmailData = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int registrationEmailLabel = 2131099694;
			
			// aapt resource value: 0x7f060031
			public const int registrationPasswordData = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int registrationPasswordLabel = 2131099696;
			
			// aapt resource value: 0x7f060023
			public const int registrierenText = 2131099683;
			
			// aapt resource value: 0x7f06002b
			public const int textView1 = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int textView2 = 2131099688;
			
			// aapt resource value: 0x7f060020
			public const int usernameText = 2131099680;
			
			// aapt resource value: 0x7f060018
			public const int verticalSeparator = 2131099672;
			
			// aapt resource value: 0x7f06002c
			public const int view1 = 2131099692;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEvent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EventsFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FillData = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FlyOutContainer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LogIn = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MenuLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NoEventsFoundFragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Registration = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int UserListView = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int server = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
